<?php

defined( 'ABSPATH' ) || exit;

class Ikon_SEO_Validator {
	private $profile;
	private $local;

	public function __construct( Ikon_SEO_Profile $profile, Ikon_SEO_Local $local ) {
		$this->profile = $profile;
		$this->local   = $local;
	}

	public function validate_page_payload( array $payload, $is_update = false ) {
		$errors = array();

		if ( ! $is_update && empty( trim( (string) ( $payload['title'] ?? '' ) ) ) ) {
			$errors[] = 'title is required';
		}

		if ( isset( $payload['title'] ) && strlen( wp_strip_all_tags( (string) $payload['title'] ) ) > 200 ) {
			$errors[] = 'title cannot exceed 200 characters';
		}

		if ( isset( $payload['mode'] ) && ! in_array( $payload['mode'], array( 'create', 'improve' ), true ) ) {
			$errors[] = 'mode must be create or improve';
		}

		if ( isset( $payload['mode'] ) && 'improve' === $payload['mode'] && empty( $payload['source_page_id'] ) ) {
			$errors[] = 'source_page_id is required in improve mode';
		}

		if ( isset( $payload['sections'] ) && ! is_array( $payload['sections'] ) ) {
			$errors[] = 'sections must be an array';
		}

		if ( ! array_key_exists( 'sections', $payload ) || ! array_key_exists( 'seo', $payload ) || ! is_array( $payload['seo'] ) ) {
			$errors[] = 'sections and seo are required';
		}

		if ( isset( $payload['sections'] ) && count( $payload['sections'] ) > 40 ) {
			$errors[] = 'sections cannot contain more than 40 items';
		}

		$section_types = array( 'content', 'cards', 'features', 'checklist', 'table', 'process', 'faq', 'related-links', 'cta', 'split-content', 'stats', 'trust', 'documents', 'notice', 'expert', 'sources', 'location-details', 'service-area', 'map', 'local-proof', 'reviews' );
		foreach ( is_array( $payload['sections'] ?? null ) ? $payload['sections'] : array() as $index => $section ) {
			if ( ! is_array( $section ) ) {
				$errors[] = 'sections.' . $index . ' must be an object';
				continue;
			}
			if ( ! in_array( sanitize_key( $section['type'] ?? 'content' ), $section_types, true ) ) {
				$errors[] = 'sections.' . $index . '.type is not supported';
			}
			if ( isset( $section['items'] ) && ( ! is_array( $section['items'] ) || count( $section['items'] ) > 30 ) ) {
				$errors[] = 'sections.' . $index . '.items must contain no more than 30 items';
			}
			if ( isset( $section['rows'] ) && ( ! is_array( $section['rows'] ) || count( $section['rows'] ) > 50 ) ) {
				$errors[] = 'sections.' . $index . '.rows must contain no more than 50 rows';
			}
			if ( 'map' === sanitize_key( $section['type'] ?? '' ) ) {
				if ( empty( $section['map_query'] ) && empty( $section['map_embed_url'] ) && empty( $section['map_url'] ) ) {
					$errors[] = 'sections.' . $index . ' map requires map_query, map_embed_url or map_url';
				}
				if ( ! empty( $section['map_embed_url'] ) ) {
					$url  = esc_url_raw( $section['map_embed_url'] );
					$host = strtolower( (string) wp_parse_url( $url, PHP_URL_HOST ) );
					$path = (string) wp_parse_url( $url, PHP_URL_PATH );
					if ( 'https' !== strtolower( (string) wp_parse_url( $url, PHP_URL_SCHEME ) ) || ! in_array( $host, array( 'www.google.com', 'maps.google.com' ), true ) || 0 !== strpos( $path, '/maps/embed' ) ) {
						$errors[] = 'sections.' . $index . '.map_embed_url must be an HTTPS Google Maps embed URL';
					}
				}
			}
		}

		if ( isset( $payload['faq'] ) && ( ! is_array( $payload['faq'] ) || count( $payload['faq'] ) > 30 ) ) {
			$errors[] = 'faq must be an array containing no more than 30 items';
		}

		if ( isset( $payload['slug'] ) && strlen( (string) $payload['slug'] ) > 200 ) {
			$errors[] = 'slug cannot exceed 200 characters';
		}

		if ( isset( $payload['seo']['description'] ) && strlen( wp_strip_all_tags( $payload['seo']['description'] ) ) > 500 ) {
			$errors[] = 'seo.description cannot exceed 500 characters';
		}

		if ( isset( $payload['seo']['canonical'] ) && $payload['seo']['canonical'] && ! wp_http_validate_url( $payload['seo']['canonical'] ) ) {
			$errors[] = 'seo.canonical must be a valid HTTP or HTTPS URL';
		}

		if ( isset( $payload['featured_media_id'] ) && ! is_numeric( $payload['featured_media_id'] ) ) {
			$errors[] = 'featured_media_id must be an attachment ID';
		}
		if ( isset( $payload['social_media_id'] ) && ! is_numeric( $payload['social_media_id'] ) ) {
			$errors[] = 'social_media_id must be an attachment ID';
		}

		$schema = is_array( $payload['schema'] ?? null ) ? $payload['schema'] : array();
		foreach ( array( 'review', 'reviews', 'aggregate_rating', 'aggregateRating' ) as $forbidden ) {
			if ( array_key_exists( $forbidden, $schema ) ) {
				$errors[] = 'review and aggregate-rating schema cannot be generated by Ikon SEO';
			}
		}
		if ( isset( $schema['page_type'] ) ) {
			$page_types = array( 'webpage', 'service', 'article', 'profile', 'collection', 'tool', 'about', 'contact', 'location', 'howto' );
			if ( ! in_array( sanitize_key( $schema['page_type'] ), $page_types, true ) ) {
				$errors[] = 'schema.page_type is not supported';
			}
		}

		$errors = array_merge( $errors, $this->profile->validate_payload( $payload ) );
		$errors = array_merge( $errors, $this->local->validate_payload( $payload ) );

		$review = is_array( $payload['content_review'] ?? null ) ? $payload['content_review'] : array();
		foreach ( (array) ( $review['sources'] ?? array() ) as $source ) {
			if ( ! wp_http_validate_url( $source ) ) {
				$errors[] = 'content_review.sources must contain valid HTTP or HTTPS URLs';
				break;
			}
		}
		foreach ( array( 'fact_checked_date', 'next_review_date' ) as $date_field ) {
			if ( empty( $review[ $date_field ] ) ) {
				continue;
			}
			$date = DateTime::createFromFormat( 'Y-m-d', (string) $review[ $date_field ] );
			if ( ! $date || $date->format( 'Y-m-d' ) !== $review[ $date_field ] ) {
				$errors[] = 'content_review.' . $date_field . ' must use YYYY-MM-DD';
			}
		}

		if ( $errors ) {
			return new WP_Error(
				'ikon_seo_invalid_payload',
				implode( '; ', $errors ),
				array( 'status' => 400, 'errors' => $errors )
			);
		}

		return true;
	}
}
